language: java
install:
  - git clone --depth=1 git://github.com/lp0/cursus.git __cursus__
  - cd __cursus__
  - mvn -q -B -V install
  - cd ..
  - rm -rf __cursus__
  - git clone --depth=1 git://github.com/lp0/cursus-core.git __cursus-core__
  - cd __cursus-core__
  - mvn -q -B -V -DskipTests=true install
  - cd ..
  - rm -rf __cursus-core__
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
after_script:
  - "[ $TRAVIS_TEST_RESULT -ne 0 ] && head -n 500 target/surefire-reports/*.txt"
